services:
  lk-jwt-service:
    image: ghcr.io/element-hq/lk-jwt-service:latest-ci
    environment:
      - LIVEKIT_JWT_PORT=8009
      - LIVEKIT_URL=wss://test1.im.avato.cc/livekit/sfu
      - LIVEKIT_KEY=devkey
      - LIVEKIT_SECRET=secret
    deploy:
      restart_policy:
        condition: on-failure
    network_mode: host

  livekit:
    image: livekit/livekit-server:latest
    command: --config /etc/livekit.yaml
    restart: unless-stopped
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml:Z
    deploy:
      restart_policy:
        condition: on-failure
    network_mode: host

  avatochat-server:
    build:
      context: ./avatochat
      dockerfile: Dockerfile
      network: host
    volumes:
      - ./avatochat:/opt/avatochat
    network_mode: host
    deploy:
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:Z
      - ../certs/crt.pem:/opt/nginx/crt.pem:Z
      - ../certs/key.pem:/opt/nginx/key.pem:Z
      - ./nginx/web:/opt/nginx/web
    depends_on:
      - avatochat-server
    network_mode: host
    deploy:
      restart_policy:
        condition: on-failure
